CREATE TABLE accounts(
    SQLID INT(11) NOT NULL AUTO_INCREMENT,
    Playername VARCHAR(64) NOT NULL DEFAULT "",
    Cash INT(11) NOT NULL DEFAULT '0',
    LEVEL INT(11) NOT NULL DEFAULT '0',
    Age INT(11) NOT NULL DEFAULT '1',
    PRIMARY KEY(SQLID)
);